require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Steepfile'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 128

Metrics/MethodLength:
  Max: 24

Metrics/ParameterLists:
  Max: 8

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Max: 18

RSpec/MultipleMemoizedHelpers:
  Max: 12

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
